version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    binary: lcli
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/suda-3156/leetcode-cli/cmd.version=v{{.Version}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

source:
  enabled: true

checksum:
  name_template: "{{ .Version }}_checksums.txt"

homebrew_casks:
  - name: lcli
    homepage: "https://github.com/suda-3156/leetcode-cli"
    description: "LeetCode CLI Tool to generate code files from LeetCode problems"
    repository:
      owner: suda-3156
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url:
      verified: github.com/suda-3156/leetcode-cli/releases/download
